---
collections:
  - name: operator_sdk.util
    version: "0.5.0"
  - name: kubernetes.core
    version: "5.1.0"
  - name: cloud.common
    version: "5.0.0"
  - name: community.docker
    version: "4.5.1"
