---
collections:
  - name: operator_sdk.util
    version: "0.5.0"
  - name: kubernetes.core
    version: "3.0.1"
  - name: cloud.common
    version: "3.0.0"
  - name: community.docker
    version: "3.10.2"
