---
- name: Create the grafanacloud.stakater.com/v1alpha1.GrafanaCloudOperator
  kubernetes.core.k8s:
    state: present
    namespace: '{{ namespace }}'
    definition: "{{ lookup('template', '/'.join([samples_dir, cr_file])) | from_yaml }}"
    wait: true
    wait_timeout: 300
    wait_condition:
      type: Successful
      status: "True"
  vars:
    cr_file: 'grafanacloud_v1alpha1_grafanacloudoperator.yaml'

- name: Add assertions here
  ansible.builtin.assert:
    that: false
    fail_msg: FIXME Add real assertions for your operator
