---
- name: Build kustomize testing overlay
  # load_restrictor must be set to none so we can load patch files from the default overlay
  ansible.builtin.command: '{{ kustomize }} build --load-restrictor LoadRestrictionsNone'
  args:
    chdir: '{{ config_dir }}/testing'
  register: resources
  changed_when: false

- name: Set resources to {{ state }}
  kubernetes.core.k8s:
    definition: '{{ item }}'
    state: '{{ state }}'
    wait: false
  loop: '{{ resources.stdout | from_yaml_all | list }}'

- name: Wait for resources to get to {{ state }}
  kubernetes.core.k8s:
    definition: '{{ item }}'
    state: '{{ state }}'
    wait: true
  loop: '{{ resources.stdout | from_yaml_all | list }}'
