---
# Namespace related defaults
grafana_cloud_operator_operator_namespace: grafana-cloud-operator
grafana_cloud_operator_service_account_name: grafana-cloud-operator-sa
grafana_cloud_operator_cluster_role_name: grafana-cloud-operator-role
grafana_cloud_operator_cluster_role_binding_name: grafana-cloud-operator-rb
grafana_cloud_operator_deployment_name: grafana-cloud-operator-deployment

# Operator image and probe configurations
grafana_cloud_operator_operator_image: "YOUR_OPERATOR_IMAGE"
grafana_cloud_operator_liveness_probe_path: /healthz
grafana_cloud_operator_readiness_probe_path: /readyz
grafana_cloud_operator_probe_initial_delay: 5
grafana_cloud_operator_probe_period: 10

# Grafana Cloud API details
grafana_cloud_operator_grafana_cloud_integrations_api_url: "https://oncall-prod-eu-west-0.grafana.net/oncall/api/v1/integrations/"
# grafana_cloud_api_token: "2aa40ff78868d8c47470c1db8efe60b31c845bb32a77b77b58229b0cbbbf74a6" # Note: Store securely or use Ansible Vault

# Alertmanager details
grafana_cloud_operator_alertmanager_namespace: openshift-monitoring
grafana_cloud_operator_alertmanager_secret_name: alertmanager-main

# SyncSet details
grafana_cloud_operator_syncset_namespace: grafana-cloud-operator


## SLO Dashboard

# URL of the Grafana Cloud dashboard API
grafana_cloud_operator_slo_cloud_api: https://stakater.grafana.net/api
# Token with permissions to interact with Grafana Cloud Dashboard

grafana_cloud_operator_slo_customer_name: customer

grafana_cloud_operator_slo_release_name: slo

# # The URL of the endpoint to send samples to
# grafana_cloud_operator_slo_remote_write_url: https://prometheus-prod-24-prod-eu-west-2.grafana.net/api/prom/push
# # Username for authentication when sending data to the remote endpoint
# grafana_cloud_operator_slo_remote_write_username:
# # Password for authentication when sending data to the remote endpoint
# grafana_cloud_operator_slo_remote_write_password:
