apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: {{ include "grafana-cloud-ansible-operator.resource" . }}-proxy-rolebinding
  labels:
    {{- include "grafana-cloud-ansible-operator.labels" . | nindent 4 }}
    app.kubernetes.io/component: kube-rbac-proxy
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: {{ include "grafana-cloud-ansible-operator.resource" . }}-proxy-role
subjects:
- kind: ServiceAccount
  name: {{ include "grafana-cloud-ansible-operator.serviceAccountName" . }}
  namespace: {{ .Release.Namespace }}
