apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: {{ include "grafana-cloud-ansible-operator.fullname" . }}-proxy-role
  labels:
    {{- include "grafana-cloud-ansible-operator.labels" . | nindent 4 }}
    app.kubernetes.io/component: kube-rbac-proxy
rules:
- apiGroups:
  - authentication.k8s.io
  resources:
  - tokenreviews
  verbs:
  - create
- apiGroups:
  - authorization.k8s.io
  resources:
  - subjectaccessreviews
  verbs:
  - create
