apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: {{ include "grafana-cloud-ansible-operator.fullname" . }}-metrics-reader
  labels:
    {{- include "grafana-cloud-ansible-operator.labels" . | nindent 4 }}
    app.kubernetes.io/component: kube-rbac-proxy
rules:
- nonResourceURLs:
  - "/metrics"
  verbs:
  - get
