apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: {{ include "grafana-cloud-ansible-operator.fullname" . }}-grafanacloudconfig-viewer-role
  labels:
    {{- include "grafana-cloud-ansible-operator.labels" . | nindent 4 }}
rules:
- apiGroups:
  - grafanacloud.stakater.com
  resources:
  - grafanacloudconfigs
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - grafanacloud.stakater.com
  resources:
  - grafanacloudconfigs/status
  verbs:
  - get
