apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: {{ include "grafana-cloud-ansible-operator.fullname" . }}-manager-role
  labels:
    {{- include "grafana-cloud-ansible-operator.labels" . | nindent 4 }}
rules:
  ##
  ## Base operator rules
  ##
  - apiGroups:
      - ""
    resources:
      - secrets
      - pods
      - pods/exec
      - pods/log
    verbs:
      - create
      - delete
      - get
      - list
      - patch
      - update
      - watch
  - apiGroups:
      - apps
    resources:
      - deployments
      - daemonsets
      - replicasets
      - statefulsets
    verbs:
      - create
      - delete
      - get
      - list
      - patch
      - update
      - watch
  ##
  ## Rules for grafanacloud.stakater.com/v1alpha1, Kind: GrafanaCloudOperator
  ##
  - apiGroups:
      - grafanacloud.stakater.com
    resources:
      - grafanacloudoperators
      - grafanacloudoperators/status
      - grafanacloudoperators/finalizers
    verbs:
      - create
      - delete
      - get
      - list
      - patch
      - update
      - watch
  - apiGroups: [""]
    resources: ["namespaces"]
    verbs: ["*"]
  - apiGroups: [""]
    resources: ["serviceaccounts"]
    verbs: ["*"]
  - apiGroups: ["rbac.authorization.k8s.io"]
    resources: ["roles", "rolebindings"]
    verbs: ["*"]
  - apiGroups: ["rbac.authorization.k8s.io"]
    resources: ["clusterroles", "clusterrolebindings"]
    verbs: ["create", "delete", "get", "list", "patch", "update", "watch"]
  - apiGroups: [""]
    resources: ["nodes"]
    verbs: ["list"]
  - apiGroups: ["hive.openshift.io"]
    resources: ["clusterdeployments"]
    verbs: ["get", "list", "watch"]
  - apiGroups: ["slack.stakater.com"]
    resources: ["channels"]
    verbs: ["get", "list", "watch"]
  - apiGroups: ["monitoring.coreos.com"]
    resources: ["prometheusrule"]
    verbs: ["get", "list", "watch"]
  - apiGroups: ["hive.openshift.io"]
    resources: ["syncsets"]
    verbs: ["*"]
  - apiGroups: [""]
    resources: ["secrets"]
    verbs: ["*"]    
#+kubebuilder:scaffold:rules
