apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "grafana-cloud-ansible-operator.serviceAccountName" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "grafana-cloud-ansible-operator.labels" . | nindent 4 }}
