---
- name: Converge
  hosts: localhost
  connection: local
  gather_facts: false

  tasks:
    - name: Build operator image
      community.docker.docker_image:
        build:
          path: '{{ project_dir }}'
          pull: false
        name: '{{ grafana_cloud_operator_operator_image }}'
        tag: latest
        push: false
        source: build
        force_source: true

    - name: Load image into kind cluster
      ansible.builtin.command: kind load docker-image --name osdk-test '{{ grafana_cloud_operator_operator_image }}'
      register: result
      changed_when: '"not yet present" in result.stdout'

- name: Import converge playbook
  import_playbook: ../default/converge.yml
