---
- name: Create
  hosts: localhost
  connection: local
  gather_facts: false
  tasks:
    - name: Create test kind cluster
      ansible.builtin.command: kind create cluster --name osdk-test --kubeconfig {{ kubeconfig }}
      changed_when: false
