apiVersion: grafanacloud.stakater.com/v1alpha1
kind: Config
metadata:
  labels:
    app.kubernetes.io/name: config
    app.kubernetes.io/instance: config-sample
    app.kubernetes.io/part-of: grafana-cloud-ansible-operator
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/created-by: grafana-cloud-ansible-operator
  name: config-sample
spec:
  enabled: true
  provisionMode: standalone # or hubAndSpoke
  grafanaAPIToken:
    secretName: grafana-api-token-secret
    key: api-token
