- name: Delete resources for standalone topology
  ansible.builtin.include_tasks: delete_grafana_oncall_standalone.yml
  when: grafana_cloud_operator_cr.spec.provisionMode == 'standalone'

- name: Remove finalizer from CR
  kubernetes.core.k8s:
    definition:
      apiVersion: grafanacloud.stakater.com/v1alpha1
      kind: Config
      metadata:
        name: "{{ grafana_cloud_operator_cr.metadata.name }}"
        namespace: "{{ grafana_cloud_operator_grafana_cloud_operator_cr_namespace }}"
        finalizers: []
    state: present
