# main.yml
- name: Set default values
  ansible.builtin.set_fact:
    state: "{{ state | default('present') }}"

- name: Include common tasks
  ansible.builtin.include_tasks: common_tasks.yml

- name: Install SLO Dashboard
  ansible.builtin.include_tasks: grafana_slo.yml
  when: gco_cr.spec.provisionMode == 'hubAndSpoke' and state != 'absent'

- name: Execute tasks for hub and spoke topology
  ansible.builtin.include_tasks: grafana_oncall_hub_spoke.yml
  when: gco_cr.spec.provisionMode == 'hubAndSpoke' and state != 'absent'

- name: Execute tasks for standalone topology
  ansible.builtin.include_tasks: grafana_oncall_standalone.yml
  when: gco_cr.spec.provisionMode == 'standalone' and state != 'absent'

- name: Execute deletion tasks
  ansible.builtin.include_tasks: grafana_oncall_delete.yml
  when: state == 'absent'
