# main.yml
- name: Include common tasks
  ansible.builtin.include_tasks: common_tasks.yml

- name: Execute tasks for hub and spoke topology
  ansible.builtin.include_tasks: grafana_oncall_hub_spoke.yml
  when: gco_cr.spec.provisionMode == 'hubAndSpoke'

- name: Execute tasks for standalone topology
  ansible.builtin.include_tasks: grafana_oncall_standalone.yml
  when: gco_cr.spec.provisionMode == 'standalone'

- name: Execute tasks for hub and spoke topology
  ansible.builtin.include_tasks: grafana_oncall_hub_spoke_delete.yml
  when: gco_cr.spec.provisionMode == 'hubAndSpoke_delete'

- name: Execute tasks for standalone topology
  ansible.builtin.include_tasks: grafana_oncall_standalone_delete.yml
  when: gco_cr.spec.provisionMode == 'standalone_delete'
