---
- name: Converge
  hosts: localhost
  connection: local
  gather_facts: false

  tasks:
    - name: Create Namespace
      kubernetes.core.k8s:
        api_version: v1
        kind: Namespace
        name: '{{ namespace | string }}'

    - name: Use kustomizations
      ansible.builtin.import_tasks: tasks/kustomize.yml
      vars:
        state: present
