---
- name: Destroy
  hosts: localhost
  connection: local
  gather_facts: false

  tasks:
    - name: Import kustomizations
      ansible.builtin.import_tasks: tasks/kustomize.yml
      vars:
        state: absent

    - name: Destroy Namespace
      kubernetes.core.k8s:
        api_version: v1
        kind: Namespace
        name: '{{ namespace }}'
        state: absent

    - name: Unset pull policy
      ansible.builtin.command: '{{ kustomize }} edit remove patch pull_policy/{{ operator_pull_policy }}.yaml'
      args:
        chdir: '{{ config_dir }}/testing'
      changed_when: false
