---
- name: Initiate Grafana Cloud Operator
  hosts: localhost
  connection: local
  gather_facts: false
  run_once: true

  tasks:
    - name: Install
      ansible.builtin.include_role:
        name: grafana_cloud_operator
      # when: >
      #   ACTION is not defined or
      #   ACTION is none or
      #   ACTION|trim() == "" or
      #   ACTION|trim() == "install"
      # tags:
      #   - always
    - name: Uninstall
      ansible.builtin.include_role:
        name: install
      # when: >
      #   ACTION is defined and
      #   ACTION|trim() == "uninstall"
      # tags:
      #   - always
