name: OperatorHub Certification

on:
  push:
    tags:
      - "v*"

jobs:
  publish-mto-to-operator-hub:
    name: publish-gco-to-operator-hub
    uses: stakater/.github/.github/workflows/publish_operator_image_and_bundle.yaml@v0.0.43
    secrets:
      REGISTRY_REDHAT_IO_PULL_SECRET: ${{ secrets.REGISTRY_REDHAT_IO_PULL_SECRET }}
      STAKATER_NEXUS_REGISTRY: ghcr.io/stakater
      STAKATER_NEXUS_USERNAME: ${{ secrets.GHCR_USERNAME }}
      STAKATER_NEXUS_PASSWORD: ${{ secrets.GHCR_TOKEN }}
      OPERATORHUB_USERNAME: ${{ secrets.OPERATOR_HUB_USERNAME }}
      OPERATORHUB_PASSWORD: ${{ secrets.OPERATOR_HUB_PASSWORD }}
      OPERATORHUB_REPOSITORY: ${{ secrets.OPERATOR_HUB_REPOSITORY }}
      PYXIS_API_TOKEN: ${{ secrets.PYXIS_API_TOKEN }}
      STAKATER_GITHUB_TOKEN: ${{ secrets.STAKATER_GITHUB_HELM_REGISTRY }}
      ADMIN_TOKEN: ${{ secrets.STAKATER_GITHUB_TOKEN }}
      STAKATER_DELIVERY_SLACK_WEBHOOK: ${{ secrets.STAKATER_DELIVERY_SLACK_WEBHOOK }}
    with:
      CERTIFICATION_PROJECT_ID: ospid-61b613641f6ce30c05d01c1a
      DOCKER_FILE_PATH: Dockerfile.operatorhub
      PUBLISH_BUNDLE: true
      SUBPATH: .
